### ISSUE TITLE
ctrl+enter to send the message in the comment part.

### ISSUE THREAD

**Issue by Natim** [ecreall/nova-ideo#14]
If you press enter you add a new line.
If you press ctrl+enter you don't send the message. It could and probably should according to other platforme (github/etc.)

**Comment by amensouissi** [comment]
Thanks!

**Comment by Natim** [comment]
Thanks to you, please create a pull request when adding new feature so that we can comment and review them before.

Your commit doesn't have a test for instance: https://github.com/ecreall/nova-ideo/commit/b168d024a07c05e3112be500abc8bde281602746

**Comment by vincentfretin** [comment]
The change is deployed.
