### ISSUE TITLE
Display a list of available variable in the email template configuration admin

### ISSUE THREAD

**Issue by Natim** [ecreall/nova-ideo#18]
It is quite easy to reuse the one that are already present in the template but if you want to add some information like the date, or the comment content you have no clue about the variable name.

Would it be:
- `{subject_content}`
- `{subject_body}`
- `{subject_description}`

**Comment by vincentfretin** [comment]
Great idea. These specific variables currently don't exist, but would be indeed nice to have.
Including the comment content in the mail notification should be the default IMHO, like github notifications. I mainly read the discussions via mail thread instead of going to github.

**Comment by vincentfretin** [comment]
The comment content is now in the mail notifications. We already had the comment_content variable in the code, so @amensouissi did the modification in the above commit at the same time of making the user title (Mr/Madam) optional.

**Comment by Natim** [comment]
Well maybe the issue about listing those variable is still accurate.

**Comment by vincentfretin** [comment]
Yes indeed, please keep it open ;)
